language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed ponzam/udagram-api-feed:v1
  - docker tag udagram-api-user ponzam/udagram-api-user:v1
  - docker tag udagram-frontend ponzam/udagram-frontend:v1
  - docker tag udagram-reverseproxy ponzam/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ponzam/udagram-api-feed:v1
  - docker push ponzam/udagram-api-user:v1
  - docker push ponzam/udagram-frontend:v1
  - docker push ponzam/udagram-reverseproxy:v1